May 14 05:10:11 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/util.py", line 51, in __koe
    func(*args, **kwargs)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/faucet.py", line 498, in handler_connect_or_disconnect
    self.handler_datapath(ryu_dp)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/faucet.py", line 523, in handler_datapath
    dp_id, discovered_up_port_nums)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/valve.py", line 569, in datapath_connect
    ofmsgs.extend(self._add_default_meters())
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/valve.py", line 409, in _add_default_meters
    print bands
NameError: global name 'bands' is not defined
May 14 05:35:33 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/util.py", line 51, in __koe
    func(*args, **kwargs)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/faucet.py", line 498, in handler_connect_or_disconnect
    self.handler_datapath(ryu_dp)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/faucet.py", line 523, in handler_datapath
    dp_id, discovered_up_port_nums)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/valve.py", line 571, in datapath_connect
    ofmsgs.extend(self._add_default_meters())
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/valve.py", line 409, in _add_default_meters
    burst_size=0))
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/valve.py", line 343, in value_meteradd
    bands=bands)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/valve_of.py", line 317, in metermod
    bands=band)
TypeError: __init__() takes at least 2 arguments (5 given)
May 14 05:36:52 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/util.py", line 51, in __koe
    func(*args, **kwargs)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/faucet.py", line 498, in handler_connect_or_disconnect
    self.handler_datapath(ryu_dp)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/faucet.py", line 523, in handler_datapath
    dp_id, discovered_up_port_nums)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/valve.py", line 571, in datapath_connect
    ofmsgs.extend(self._add_default_meters())
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/valve.py", line 409, in _add_default_meters
    burst_size=0))
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/valve.py", line 343, in value_meteradd
    bands=bands)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/valve_of.py", line 317, in metermod
    bands=band)
TypeError: __init__() takes at least 2 arguments (5 given)
May 14 07:57:58 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/util.py", line 51, in __koe
    func(*args, **kwargs)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/faucet.py", line 498, in handler_connect_or_disconnect
    self.handler_datapath(ryu_dp)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/faucet.py", line 523, in handler_datapath
    dp_id, discovered_up_port_nums)
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/valve.py", line 583, in datapath_connect
    ofmsgs.extend(self._add_default_meters())
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/valve.py", line 406, in _add_default_meters
    burst_size=0))
  File "/home/mininet/faucet/src/ryu_faucet/org/onfsdn/faucet/valve_of.py", line 325, in dropband
    burst_size=burst_size
TypeError: __init__() got an unexpected keyword argument 'len'
